repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 38b88246ccc552bffaaf54259d064beeee434539 # frozen: v4.0.1
    hooks:
      - id: check-ast
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-docstring-first
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: check-json
      # check for file bigger than 500kb
      - id: check-added-large-files
      - id: check-yaml
      - id: debug-statements
      - id: fix-encoding-pragma
        args: [--remove]

  - repo: https://github.com/Trim21/pre-commit-hooks
    rev: e4bd622f56f4cb289b7c15f6e9f03698afbc55d2 # frozen: v0.4.1
    hooks:
      - id: find-trailing-comma
      - id: poetry-check-lock

  - repo: https://github.com/asottile/pyupgrade
    rev: 486760aeedfeed700b8fa8b359ba91f77d540ec4 # frozen: v2.26.0
    hooks:
      - id: pyupgrade
        args: ["--py37-plus"]

  - repo: https://github.com/myint/autoflake
    rev: 7a53fdafc82c33f446915b60fcac947c51279260 # frozen: v1.4
    hooks:
      - id: autoflake
        args:
          - --in-place
          - --remove-unused-variables
          - --remove-all-unused-imports
          - --expand-star-imports

  - repo: https://github.com/timothycrosley/isort
    rev: fd5ba70665a37ec301a1f714ed09336048b3be63 # frozen: 5.9.3
    hooks:
      - id: isort
        require_serial: true
        args:
          [
            "--line-width=88",
            "--trailing-comma",
            "--multi-line=3",
            "--project=trim21_flexget_plugins",
            "--section-default=THIRDPARTY",
          ]

  - repo: https://github.com/psf/black
    rev: 911470a610e47d9da5ea938b0887c3df62819b85 # frozen: 21.9b0
    hooks:
      - id: black
