repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3298ddab3c13dd77d6ce1fc0baf97691430d84b0 # frozen: v4.3.0
    hooks:
      - id: check-ast
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-docstring-first
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: check-json
      # check for file bigger than 500kb
      - id: check-added-large-files
      - id: check-yaml
      - id: debug-statements
      - id: fix-encoding-pragma
        args: [--remove]

  - repo: https://github.com/Trim21/pre-commit-hooks
    rev: 2cd566d7d05582364aaa111f4522efd33857346c # frozen: v0.5.1
    hooks:
      - id: find-trailing-comma
      - id: poetry-check-lock

  - repo: https://github.com/asottile/pyupgrade
    rev: d50ce21fc45d014790d4ecf71d1b1d7ccc450526 # frozen: v3.1.0
    hooks:
      - id: pyupgrade
        args: ["--py37-plus"]

  - repo: https://github.com/myint/autoflake
    rev: d603145783430b4e0f9ec3ab0227e194ad5d1d49 # frozen: v1.7.4
    hooks:
      - id: autoflake
        args:
          - --in-place
          - --remove-unused-variables
          - --remove-all-unused-imports
          - --expand-star-imports

  - repo: https://github.com/PyCQA/flake8
    rev: f8e1b317742036ff11ff86356fd2b68147e169f7 # frozen: 5.0.4
    hooks:
      - id: flake8
        args:
          - --ignore=C0103,C0111,R0903,W503,W504,C812,C813,C815,C819,B008,E265,E501

  - repo: https://github.com/timothycrosley/isort
    rev: c5e8fa75dda5f764d20f66a215d71c21cfa198e1 # frozen: 5.10.1
    hooks:
      - id: isort
        require_serial: true
        args:
          [
            "--line-width=88",
            "--trailing-comma",
            "--multi-line=3",
            "--project=trim21_flexget_plugins",
            "--section-default=THIRDPARTY",
          ]

  - repo: https://github.com/psf/black
    rev: 27d20144a7517594e24a1649451177b2a11284be # frozen: 22.10.0
    hooks:
      - id: black
