name: ci

on:
  push:
    branches-ignore:
      - renovate/**
      - deepsource-fix-*
  pull_request: {}

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.7", "3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - uses: Trim21/setup-poetry@dist/v1

      - uses: Trim21/install-poetry-project@dist/v1

      - name: test
        run: coverage run -m pytest

      - run: coverage xml

      - uses: codecov/codecov-action@v3
        with:
          flags: ${{ matrix.python }}

  dist-files:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - uses: Trim21/setup-poetry@dist/v1

      - run: poetry build

      - name: Install twine
        run: pip install twine

      - name: Check Files
        run: twine check dist/*
